# Generated by Django 2.0.1 on 2018-01-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='url',
        ),
        migrations.AddField(
            model_name='channel',
            name='path',
            field=models.CharField(default='1', max_length=1024),
            preserve_default=False,
        ),
    ]
