# Generated by Django 2.0.1 on 2018-01-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Playlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='public_key',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
