# Generated by Django 2.0.1 on 2018-01-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_playlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='app.Playlist'),
        ),
    ]
