# Generated by Django 2.0.1 on 2018-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180106_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hide from public playlist'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='length',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='channel',
            name='path',
            field=models.CharField(max_length=1024, verbose_name='path to *.m3u8'),
        ),
    ]
