# Generated by Django 2.0.1 on 2018-01-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180110_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='length',
            new_name='duration',
        ),
    ]
