# Generated by Django 2.0.1 on 2018-01-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180110_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='duration',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='path',
            field=models.CharField(max_length=1024, verbose_name='path to content'),
        ),
    ]
