# Generated by Django 2.0.2 on 2018-02-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180217_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='path',
            field=models.TextField(verbose_name='Path to content'),
        ),
    ]
