# Generated by Django 2.0.2 on 2018-03-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180310_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('-title',)},
        ),
    ]
