# Generated by Django 2.0.2 on 2018-03-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180312_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('title',)},
        ),
    ]
