# Generated by Django 2.0.2 on 2018-03-12 17:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_auto_20180312_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='playlists', validators=[django.core.validators.FileExtensionValidator(['m3u8', 'm3u'])])),
                ('url', models.URLField(blank=True, null=True)),
                ('remove_existed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='app.Playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
