# Generated by Django 2.0.2 on 2018-06-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_channel_user(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Channel = apps.get_model('app', 'Channel')
    for channel in Channel.objects.filter(user__isnull=True):
        channel.user = channel.playlist.user
        channel.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_auto_20180312_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_channel_user),
    ]
