# Generated by Django 2.0.6 on 2018-06-10 12:31

from django.db import migrations, models


def populate_playlists(apps, schema_editor):
    Channel = apps.get_model('app', 'Channel')
    for channel in Channel.objects.all():
        channel.playlists.add(channel.playlist)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180610_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='app.Playlist'),
        ),
        migrations.RunPython(populate_playlists),
    ]
