# Generated by Django 2.0.6 on 2018-06-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_channel_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='playlist',
        ),
    ]
