# Generated by Django 2.0.6 on 2018-06-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_channel_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedplaylist',
            name='playlist',
        ),
    ]
